name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore
      working-directory: DbDeltaWatcher
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: DbDeltaWatcher
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: DbDeltaWatcher
